type PublicationStatus = 'pending' | 'approved' | 'rejected' | 'publishing' | 'published' | 'failed';
type Sighting = { id: string; latitude: number; longitude: number; imageUrl: string; thumbnailUrl: string; createdAt: string; status: 'active' | 'disabled'; reportCount: number; instagramConsent: boolean; publicationStatus: PublicationStatus | null };
type Report = { id: string; sightingId: string; reason: string; createdAt: string };
const byId = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;
const loginView = byId<HTMLElement>('login-view'); const adminView = byId<HTMLElement>('admin-view'); const list = byId<HTMLElement>('admin-list'); const reportList = byId<HTMLElement>('report-list'); const loginStatus = byId<HTMLElement>('login-status'); const adminStatus = byId<HTMLElement>('admin-status'); const logout = byId<HTMLButtonElement>('logout'); const metaStatus = byId<HTMLElement>('meta-status');
function setStatus(element: HTMLElement, message = '', state = ''): void { element.textContent = message; element.dataset.state = state; } function date(value: string): string { return new Intl.DateTimeFormat('de-DE', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
async function request(url: string, options: RequestInit = {}): Promise<Response> { return fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers ?? {}) }, credentials: 'same-origin' }); }
function action(label: string, endpoint: string, body?: Record<string, string>): HTMLButtonElement { const button = document.createElement('button'); button.className = 'secondary-button'; button.type = 'button'; button.textContent = label; button.addEventListener('click', async () => { await mutate(endpoint, { method: 'POST', body: body ? JSON.stringify(body) : undefined }); }); return button; }
function renderInstagramActions(sighting: Sighting, actions: HTMLElement): void {
  if (!sighting.instagramConsent || !sighting.publicationStatus) return;
  const state = document.createElement('p'); state.className = 'admin-state'; state.textContent = `Instagram: ${sighting.publicationStatus}`; actions.before(state);
  if (['pending', 'failed', 'approved'].includes(sighting.publicationStatus)) {
    actions.append(action('Für Instagram freigeben', `/api/admin/sightings/${encodeURIComponent(sighting.id)}/instagram/approve`));
    actions.append(action('Instagram ablehnen', `/api/admin/sightings/${encodeURIComponent(sighting.id)}/instagram/reject`));
  }
  if (sighting.publicationStatus === 'approved') actions.append(action('Jetzt auf Instagram veröffentlichen', `/api/admin/sightings/${encodeURIComponent(sighting.id)}/instagram/publish`));
}
function renderSightings(sightings: Sighting[]): void { list.replaceChildren(); if (!sightings.length) { list.textContent = 'Keine Sichtungen vorhanden.'; return; } for (const sighting of sightings) { const card = document.createElement('article'); card.className = 'admin-card'; card.innerHTML = `<img src="${sighting.thumbnailUrl}" alt="Vorschau der Sichtung" /><div><p class="admin-state" data-state="${sighting.status}">${sighting.status === 'active' ? 'Öffentlich sichtbar' : 'Deaktiviert'}</p><time>${date(sighting.createdAt)}</time><p>${sighting.latitude.toFixed(5)}, ${sighting.longitude.toFixed(5)}</p><p class="admin-report-count">${sighting.reportCount ? `${sighting.reportCount} offene Meldung${sighting.reportCount === 1 ? '' : 'en'}` : 'Keine offenen Meldungen'}</p><div class="admin-actions"></div></div>`; const actions = card.querySelector<HTMLElement>('.admin-actions')!; const toggle = action(sighting.status === 'active' ? 'Deaktivieren' : 'Reaktivieren', `/api/admin/sightings/${encodeURIComponent(sighting.id)}/${sighting.status === 'active' ? 'deactivate' : 'reactivate'}`); const remove = document.createElement('button'); remove.className = 'admin-delete'; remove.type = 'button'; remove.textContent = 'Endgültig löschen'; remove.addEventListener('click', async () => { if (window.confirm('Diese Sichtung einschließlich aller Meldungen, Originalbild und Vorschau endgültig löschen? Diese Aktion kann nicht rückgängig gemacht werden.')) await mutate(`/api/admin/sightings/${encodeURIComponent(sighting.id)}`, { method: 'DELETE' }); }); actions.append(toggle, remove); renderInstagramActions(sighting, actions); list.append(card); } }
function renderReports(reports: Report[]): void { reportList.replaceChildren(); if (!reports.length) { reportList.textContent = 'Keine offenen Meldungen.'; return; } for (const report of reports) { const item = document.createElement('article'); item.className = 'admin-report'; const content = document.createElement('div'); const reportedAt = document.createElement('time'); reportedAt.textContent = date(report.createdAt); const reason = document.createElement('p'); reason.textContent = report.reason; const link = document.createElement('a'); link.href = `/fundort.html?id=${encodeURIComponent(report.sightingId)}`; link.target = '_blank'; link.rel = 'noopener noreferrer'; link.textContent = 'Fundort öffnen ↗'; const resolve = action('Meldung erledigen', `/api/admin/reports/${encodeURIComponent(report.id)}/resolve`); content.append(reportedAt, reason, link); item.append(content, resolve); reportList.append(item); } }
async function load(): Promise<void> { const [sightingResponse, reportResponse, metaResponse] = await Promise.all([request('/api/admin/sightings'), request('/api/admin/reports'), request('/api/admin/meta/status')]); if (!sightingResponse.ok || !reportResponse.ok || !metaResponse.ok) throw new Error('Die Verwaltungsdaten konnten nicht geladen werden.'); renderSightings((await sightingResponse.json() as { sightings: Sighting[] }).sightings); renderReports((await reportResponse.json() as { reports: Report[] }).reports); const meta = await metaResponse.json() as { connected: boolean; username: string | null }; metaStatus.textContent = meta.connected ? `Verbunden${meta.username ? ` als @${meta.username}` : ''}.` : 'Nicht verbunden.'; }
async function mutate(url: string, options: RequestInit): Promise<void> { try { const response = await request(url, options); if (!response.ok) throw new Error(); setStatus(adminStatus, 'Änderung gespeichert.', 'success'); await load(); } catch { setStatus(adminStatus, 'Die Änderung konnte nicht gespeichert werden.', 'error'); } }
async function showAdmin(): Promise<void> { try { const response = await request('/api/admin/session'); if (!response.ok) throw new Error(); loginView.hidden = true; adminView.hidden = false; logout.hidden = false; const meta = new URLSearchParams(window.location.search).get('meta'); if (meta) setStatus(adminStatus, meta === 'connected' ? 'Instagram wurde verbunden.' : 'Instagram-Verbindung fehlgeschlagen.', meta === 'connected' ? 'success' : 'error'); await load(); } catch { loginView.hidden = false; adminView.hidden = true; logout.hidden = true; } }
byId<HTMLFormElement>('login-form').addEventListener('submit', async (event) => { event.preventDefault(); setStatus(loginStatus, 'Anmeldung wird geprüft …'); const response = await request('/api/admin/login', { method: 'POST', body: JSON.stringify({ username: byId<HTMLInputElement>('username').value, password: byId<HTMLInputElement>('password').value }) }); if (!response.ok) { setStatus(loginStatus, 'Anmeldung nicht möglich.', 'error'); return; } setStatus(loginStatus); await showAdmin(); }); logout.addEventListener('click', async () => { await request('/api/admin/logout', { method: 'POST' }); await showAdmin(); }); void showAdmin();
