import { Pool } from 'pg';

export type LocationSource = 'manual' | 'exif' | 'unknown';
export type Sighting = { id: string; latitude: number; longitude: number; locationSource: LocationSource; locationDescription: string | null; imageUrl: string; thumbnailUrl: string; createdAt: string };
export type PublicationStatus = 'pending' | 'approved' | 'rejected' | 'publishing' | 'published' | 'failed';
export type AdminSighting = Sighting & { status: 'active' | 'disabled'; reportCount: number; instagramConsent: boolean; publicationStatus: PublicationStatus | null };
export type Report = { id: string; sightingId: string; reason: string; createdAt: string };
export type InstagramConnection = { pageId: string; instagramAccountId: string; username: string | null; accessToken: string };
export type InstagramPublication = { sightingId: string; imageFilename: string; status: PublicationStatus; caption: string | null; error: string | null };
type SightingRow = { id: string; latitude: number; longitude: number; location_source: LocationSource; location_description: string | null; image_filename: string; thumbnail_filename: string | null; status: 'active' | 'disabled'; created_at: Date; report_count: number | string; instagram_consent: boolean; publication_status: PublicationStatus | null };
const baseSelect = `SELECT s.id, s.latitude, s.longitude, s.location_source, s.location_description, s.image_filename, s.thumbnail_filename, s.status, s.created_at, s.instagram_consent, p.status AS publication_status, COUNT(r.id) FILTER (WHERE r.status = 'open') AS report_count FROM sightings s LEFT JOIN reports r ON r.sighting_id = s.id LEFT JOIN instagram_publications p ON p.sighting_id = s.id`;
function toSighting(row: SightingRow): Sighting { return { id: row.id, latitude: row.latitude, longitude: row.longitude, locationSource: row.location_source, locationDescription: row.location_description, imageUrl: `/uploads/${encodeURIComponent(row.image_filename)}`, thumbnailUrl: `/uploads/${encodeURIComponent(row.thumbnail_filename ?? row.image_filename)}`, createdAt: row.created_at.toISOString() }; }
export function createDatabase(connectionString: string): Pool { return new Pool({ connectionString }); }
export async function initialiseDatabase(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS sightings (id UUID PRIMARY KEY, latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90), longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180), image_filename TEXT NOT NULL, thumbnail_filename TEXT, location_description TEXT, location_description_interpreted BOOLEAN NOT NULL DEFAULT FALSE, location_description_prompt_version TEXT NOT NULL DEFAULT 'v1', status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')), instagram_consent BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    ALTER TABLE sightings ADD COLUMN IF NOT EXISTS thumbnail_filename TEXT;
    ALTER TABLE sightings ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
    ALTER TABLE sightings ADD COLUMN IF NOT EXISTS location_source TEXT NOT NULL DEFAULT 'unknown' CHECK (location_source IN ('manual', 'exif', 'unknown'));
    ALTER TABLE sightings ADD COLUMN IF NOT EXISTS instagram_consent BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE sightings ADD COLUMN IF NOT EXISTS location_description TEXT;
    ALTER TABLE sightings ADD COLUMN IF NOT EXISTS location_description_interpreted BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE sightings ADD COLUMN IF NOT EXISTS location_description_prompt_version TEXT NOT NULL DEFAULT 'v1';
    CREATE TABLE IF NOT EXISTS reports (id UUID PRIMARY KEY, sighting_id UUID NOT NULL REFERENCES sightings(id) ON DELETE CASCADE, reason TEXT NOT NULL CHECK (char_length(reason) BETWEEN 5 AND 1000), status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), resolved_at TIMESTAMPTZ);
    CREATE TABLE IF NOT EXISTS instagram_publications (sighting_id UUID PRIMARY KEY REFERENCES sightings(id) ON DELETE CASCADE, status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'publishing', 'published', 'failed')), caption TEXT, meta_media_id TEXT, error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), published_at TIMESTAMPTZ);
    CREATE TABLE IF NOT EXISTS instagram_connection (singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton), page_id TEXT NOT NULL, instagram_account_id TEXT NOT NULL, username TEXT, access_token TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS sightings_created_at_idx ON sightings (created_at DESC);
    CREATE INDEX IF NOT EXISTS sightings_status_idx ON sightings (status);
    CREATE INDEX IF NOT EXISTS reports_status_created_at_idx ON reports (status, created_at DESC);
    CREATE INDEX IF NOT EXISTS instagram_publications_status_created_at_idx ON instagram_publications (status, created_at DESC);
  `);
}
export async function listSightings(pool: Pool): Promise<Sighting[]> { const result = await pool.query<SightingRow>(`${baseSelect} WHERE s.status = 'active' GROUP BY s.id, p.status ORDER BY s.created_at DESC`); return result.rows.map(toSighting); }
export async function listSightingsMissingLocationDescriptions(pool: Pool): Promise<Array<Pick<Sighting, 'id' | 'latitude' | 'longitude'>>> { const result = await pool.query<{ id: string; latitude: number; longitude: number }>(`SELECT id, latitude, longitude FROM sightings WHERE location_description IS NULL OR location_description_interpreted = FALSE OR location_description_prompt_version <> '2026-09-25-v5' ORDER BY created_at ASC`); return result.rows; }
export async function setLocationDescription(pool: Pool, id: string, locationDescription: string, interpreted: boolean, promptVersion: string): Promise<void> { await pool.query(`UPDATE sightings SET location_description = $2, location_description_interpreted = $3, location_description_prompt_version = $4 WHERE id = $1 AND (location_description IS NULL OR location_description_interpreted = FALSE OR location_description_prompt_version <> $4)`, [id, locationDescription, interpreted, promptVersion]); }
export async function listAdminSightings(pool: Pool): Promise<AdminSighting[]> { const result = await pool.query<SightingRow>(`${baseSelect} GROUP BY s.id, p.status ORDER BY s.created_at DESC`); return result.rows.map((row) => ({ ...toSighting(row), status: row.status, reportCount: Number(row.report_count), instagramConsent: row.instagram_consent, publicationStatus: row.publication_status })); }
export async function listOpenReports(pool: Pool): Promise<Report[]> { const result = await pool.query<{ id: string; sighting_id: string; reason: string; created_at: Date }>(`SELECT id, sighting_id, reason, created_at FROM reports WHERE status = 'open' ORDER BY created_at DESC`); return result.rows.map((row) => ({ id: row.id, sightingId: row.sighting_id, reason: row.reason, createdAt: row.created_at.toISOString() })); }
export async function createReport(pool: Pool, report: { id: string; sightingId: string; reason: string }): Promise<boolean> { const result = await pool.query(`INSERT INTO reports (id, sighting_id, reason) SELECT $1, id, $3 FROM sightings WHERE id = $2 AND status = 'active'`, [report.id, report.sightingId, report.reason]); return result.rowCount === 1; }
export async function resolveReport(pool: Pool, id: string): Promise<boolean> { const result = await pool.query(`UPDATE reports SET status = 'resolved', resolved_at = NOW() WHERE id = $1 AND status = 'open'`, [id]); return result.rowCount === 1; }
export async function findActiveUpload(pool: Pool, filename: string): Promise<string | null> { const result = await pool.query<{ filename: string }>(`SELECT image_filename AS filename FROM sightings WHERE status = 'active' AND image_filename = $1 UNION ALL SELECT thumbnail_filename AS filename FROM sightings WHERE status = 'active' AND thumbnail_filename = $1 LIMIT 1`, [filename]); return result.rows[0]?.filename ?? null; }
export async function setSightingStatus(pool: Pool, id: string, status: 'active' | 'disabled'): Promise<boolean> { const result = await pool.query('UPDATE sightings SET status = $2 WHERE id = $1', [id, status]); return result.rowCount === 1; }
export async function deleteSighting(pool: Pool, id: string): Promise<{ imageFilename: string; thumbnailFilename: string | null } | null> { const result = await pool.query<{ image_filename: string; thumbnail_filename: string | null }>('DELETE FROM sightings WHERE id = $1 RETURNING image_filename, thumbnail_filename', [id]); const row = result.rows[0]; return row ? { imageFilename: row.image_filename, thumbnailFilename: row.thumbnail_filename } : null; }
export async function createSighting(pool: Pool, sighting: { id: string; latitude: number; longitude: number; locationSource: LocationSource; imageFilename: string; thumbnailFilename: string; instagramConsent: boolean }): Promise<void> { await pool.query(`INSERT INTO sightings (id, latitude, longitude, location_source, image_filename, thumbnail_filename, instagram_consent) VALUES ($1, $2, $3, $4, $5, $6, $7)`, [sighting.id, sighting.latitude, sighting.longitude, sighting.locationSource, sighting.imageFilename, sighting.thumbnailFilename, sighting.instagramConsent]); }
export async function createInstagramPublication(pool: Pool, sightingId: string): Promise<void> { await pool.query(`INSERT INTO instagram_publications (sighting_id) SELECT id FROM sightings WHERE id = $1 AND instagram_consent = TRUE ON CONFLICT (sighting_id) DO NOTHING`, [sightingId]); }
export async function setInstagramPublicationStatus(pool: Pool, sightingId: string, status: 'approved' | 'rejected', caption: string | null = null): Promise<boolean> { const result = await pool.query(`UPDATE instagram_publications SET status = $2, caption = COALESCE($3, caption), error = NULL, updated_at = NOW() WHERE sighting_id = $1 AND status IN ('pending', 'approved', 'failed')`, [sightingId, status, caption]); return result.rowCount === 1; }
export async function claimInstagramPublication(pool: Pool, sightingId: string): Promise<InstagramPublication | null> { const result = await pool.query<{ sighting_id: string; image_filename: string; status: PublicationStatus; caption: string | null; error: string | null }>(`UPDATE instagram_publications p SET status = 'publishing', error = NULL, updated_at = NOW() FROM sightings s WHERE p.sighting_id = s.id AND p.sighting_id = $1 AND p.status = 'approved' AND s.status = 'active' RETURNING p.sighting_id, s.image_filename, p.status, p.caption, p.error`, [sightingId]); const row = result.rows[0]; return row ? { sightingId: row.sighting_id, imageFilename: row.image_filename, status: row.status, caption: row.caption, error: row.error } : null; }
export async function completeInstagramPublication(pool: Pool, sightingId: string, mediaId: string): Promise<void> { await pool.query(`UPDATE instagram_publications SET status = 'published', meta_media_id = $2, error = NULL, published_at = NOW(), updated_at = NOW() WHERE sighting_id = $1 AND status = 'publishing'`, [sightingId, mediaId]); }
export async function failInstagramPublication(pool: Pool, sightingId: string, error: string): Promise<void> { await pool.query(`UPDATE instagram_publications SET status = 'failed', error = $2, updated_at = NOW() WHERE sighting_id = $1 AND status = 'publishing'`, [sightingId, error.slice(0, 500)]); }
export async function saveInstagramConnection(pool: Pool, connection: InstagramConnection): Promise<void> { await pool.query(`INSERT INTO instagram_connection (singleton, page_id, instagram_account_id, username, access_token) VALUES (TRUE, $1, $2, $3, $4) ON CONFLICT (singleton) DO UPDATE SET page_id = EXCLUDED.page_id, instagram_account_id = EXCLUDED.instagram_account_id, username = EXCLUDED.username, access_token = EXCLUDED.access_token, updated_at = NOW()`, [connection.pageId, connection.instagramAccountId, connection.username, connection.accessToken]); }
export async function getSavedInstagramConnection(pool: Pool): Promise<InstagramConnection | null> { const result = await pool.query<{ page_id: string; instagram_account_id: string; username: string | null; access_token: string }>(`SELECT page_id, instagram_account_id, username, access_token FROM instagram_connection WHERE singleton = TRUE`); const row = result.rows[0]; return row ? { pageId: row.page_id, instagramAccountId: row.instagram_account_id, username: row.username, accessToken: row.access_token } : null; }
